version: '3.8'

services:
  database:
    container_name: database
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: elonisgreat
      MARIADB_DATABASE: nyandb
      MARIADB_USER: webapp
      MARIADB_PASSWORD: startshipisready
    volumes:
      - ./database/init.sql/:/docker-entrypoint-initdb.d/:ro
    restart: always
