version: '3.8'

services:
  nyanair-nginx:
    container_name: nyanair-nginx
    image: nginx:latest
    volumes:
      - ./webapp-laravel/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    networks:
      - nyanair-net 
    depends_on:
      - nyanair-fpm

  nyanair-fpm:
    container_name: nyanair-web
    build: 
      context: ./webapp-laravel/src/
      dockerfile: ../Dockerfile
      #image: nyanair-web
    volumes:
      - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
    ports:
      - 9000:9000
    networks:
      - nyanair-net 
    depends_on:
      - database2

  database2:
    container_name: database2
    image: mariadb
    ports:
      - 3306:3306
    networks:
      - nyanair-net 
    environment:
      MARIADB_ROOT_PASSWORD: elonisgreat
      MARIADB_DATABASE: nyandb
      MARIADB_USER: webapp
      MARIADB_PASSWORD: startshipisready
    volumes:
      - ./database/init.sql/:/docker-entrypoint-initdb.d/:ro
      - mariadb-data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 20s
      retries: 10

  checkin:
    container_name: checkin
    build:
      context: ./checkin/src/
      dockerfile: ../Dockerfile
    ports:
      - 5000:5000
    networks:
      - nyanair-net 
    environment:
      DB_CONNECTION: mysql
      DB_HOST: database2
      DB_PORT: 3306
      DB_DATABASE: nyandb
      DB_USERNAME: root
      DB_PASSWORD: elonisgreat
    depends_on:
      - database2
    restart: always

volumes:
  mariadb-data:

networks:
  nyanair-net:
    driver: bridge
